export const ROUTES = {
  HOME: "/",
  CATALOG: "/catalog",
  LISTING_DETAIL: (id: string) => `/catalog/${id}`,
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    MFA: "/auth/verify-mfa",
  },
  WALLET: "/wallet",
  WALLET_TOP_UP: "/wallet/top-up",
  WALLET_WITHDRAW: "/wallet/withdraw",
  MY_BIDS: "/my-bids",
  MY_LISTINGS: "/seller/listings",
  CREATE_LISTING: "/seller/listings/new",
  EDIT_LISTING: (id: string) => `/seller/listings/${id}/edit`,
  ORDERS: "/orders",
  ORDER_DETAIL: (id: string) => `/orders/${id}`,
  NOTIFICATIONS: "/notifications",
  NOTIFICATION_PREFERENCES: "/notifications/preferences",
  PROFILE: "/profile",
  SETTINGS: "/settings",
} as const;
